// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_the_bumpy_ride = "CgkI2MHH0JQJEAIQNw"; // <GPGSID>
        public const string achievement_bouncy = "CgkI2MHH0JQJEAIQJw"; // <GPGSID>
        public const string achievement_buck_well_spent = "CgkI2MHH0JQJEAIQGQ"; // <GPGSID>
        public const string achievement_put_the_pedal_to_metal = "CgkI2MHH0JQJEAIQOQ"; // <GPGSID>
        public const string achievement_couldnt_care_less = "CgkI2MHH0JQJEAIQNg"; // <GPGSID>
        public const string achievement_near_squeak = "CgkI2MHH0JQJEAIQHg"; // <GPGSID>
        public const string achievement_thunderstruck = "CgkI2MHH0JQJEAIQLQ"; // <GPGSID>
        public const string achievement_blood_money = "CgkI2MHH0JQJEAIQNA"; // <GPGSID>
        public const string achievement_jack_of_all_trades = "CgkI2MHH0JQJEAIQGw"; // <GPGSID>
        public const string achievement_alive_and_kicking = "CgkI2MHH0JQJEAIQKg"; // <GPGSID>
        public const string achievement_elixir_of_life = "CgkI2MHH0JQJEAIQPw"; // <GPGSID>
        public const string achievement_hey_look_out = "CgkI2MHH0JQJEAIQJA"; // <GPGSID>
        public const string achievement_the_end_of_apologue = "CgkI2MHH0JQJEAIQSg"; // <GPGSID>
        public const string achievement_a_magical_number = "CgkI2MHH0JQJEAIQRw"; // <GPGSID>
        public const string achievement_a_hidden_talent = "CgkI2MHH0JQJEAIQRQ"; // <GPGSID>
        public const string achievement_ace = "CgkI2MHH0JQJEAIQJg"; // <GPGSID>
        public const string achievement_the_story = "CgkI2MHH0JQJEAIQGg"; // <GPGSID>
        public const string achievement_handle_with_care = "CgkI2MHH0JQJEAIQMQ"; // <GPGSID>
        public const string achievement_pride_and_joy = "CgkI2MHH0JQJEAIQQg"; // <GPGSID>
        public const string achievement_a_pot_of_gold = "CgkI2MHH0JQJEAIQIA"; // <GPGSID>
        public const string achievement_icarus_initiated = "CgkI2MHH0JQJEAIQHA"; // <GPGSID>
        public const string achievement_icarus_fall = "CgkI2MHH0JQJEAIQKA"; // <GPGSID>
        public const string achievement_the_lucky_duck = "CgkI2MHH0JQJEAIQNQ"; // <GPGSID>
        public const string leaderboard_digital_leaders = "CgkI2MHH0JQJEAIQAg"; // <GPGSID>
        public const string achievement_adroit = "CgkI2MHH0JQJEAIQHw"; // <GPGSID>
        public const string achievement_the_olympic_ideal = "CgkI2MHH0JQJEAIQRg"; // <GPGSID>
        public const string achievement_on_your_bike = "CgkI2MHH0JQJEAIQIQ"; // <GPGSID>
        public const string achievement_the_pantomath = "CgkI2MHH0JQJEAIQFg"; // <GPGSID>
        public const string achievement_by_the_skin_of_your_teeth = "CgkI2MHH0JQJEAIQMA"; // <GPGSID>
        public const string achievement_recovery = "CgkI2MHH0JQJEAIQJQ"; // <GPGSID>
        public const string achievement_drunk_truck = "CgkI2MHH0JQJEAIQIg"; // <GPGSID>
        public const string achievement_road_rage = "CgkI2MHH0JQJEAIQHQ"; // <GPGSID>
        public const string achievement_dare_devil = "CgkI2MHH0JQJEAIQQQ"; // <GPGSID>
        public const string achievement_deep_pockets = "CgkI2MHH0JQJEAIQGA"; // <GPGSID>
        public const string achievement_crackerjack = "CgkI2MHH0JQJEAIQFw"; // <GPGSID>
        public const string achievement_the_fatalist = "CgkI2MHH0JQJEAIQPQ"; // <GPGSID>
        public const string achievement_tour_de_force = "CgkI2MHH0JQJEAIQPg"; // <GPGSID>
        public const string achievement_a_stroke_of_genius = "CgkI2MHH0JQJEAIQRA"; // <GPGSID>
        public const string achievement_heart_stopper = "CgkI2MHH0JQJEAIQIw"; // <GPGSID>
        public const string achievement_field_marshall = "CgkI2MHH0JQJEAIQKQ"; // <GPGSID>
        public const string achievement_son_of_a_gun = "CgkI2MHH0JQJEAIQOg"; // <GPGSID>
        public const string achievement_a__true_professional = "CgkI2MHH0JQJEAIQSA"; // <GPGSID>
        public const string achievement_strike_it_rich = "CgkI2MHH0JQJEAIQSQ"; // <GPGSID>
        public const string achievement_hop_skip_and_jump = "CgkI2MHH0JQJEAIQMw"; // <GPGSID>
        public const string achievement_a_maestro = "CgkI2MHH0JQJEAIQOA"; // <GPGSID>
        public const string achievement_an_immortal = "CgkI2MHH0JQJEAIQLg"; // <GPGSID>
        public const string achievement_a_call_of_duty = "CgkI2MHH0JQJEAIQKw"; // <GPGSID>
        public const string achievement_another_day_another_dollar = "CgkI2MHH0JQJEAIQLA"; // <GPGSID>
        public const string achievement_war_torn = "CgkI2MHH0JQJEAIQPA"; // <GPGSID>
        public const string achievement_rebirth = "CgkI2MHH0JQJEAIQQw"; // <GPGSID>
        public const string achievement_want_you_for_us_amy = "CgkI2MHH0JQJEAIQLw"; // <GPGSID>
        public const string achievement_the_new_beginning = "CgkI2MHH0JQJEAIQFQ"; // <GPGSID>
        public const string achievement_break_the_bank = "CgkI2MHH0JQJEAIQOw"; // <GPGSID>
        public const string achievement_ride_the_light = "CgkI2MHH0JQJEAIQSw"; // <GPGSID>
        public const string achievement_one_jump_ahead = "CgkI2MHH0JQJEAIQQA"; // <GPGSID>
        public const string achievement_chin_up = "CgkI2MHH0JQJEAIQMg"; // <GPGSID>

}

